-- ApiKey enterprise fields: description, IP whitelist, usage counters
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "ipWhitelist" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "requestCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "errorCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "uploadCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "uploadBytes" BIGINT NOT NULL DEFAULT 0;
