import { z } from "zod";
import { safeTrim } from "@/lib/safe-string";

/** Normalize text into a URL-safe slug. Never throws. */
export function slugify(text: string | null | undefined): string {
  const value = safeTrim(text);
  if (!value) return "";
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export type SlugResolveResult = {
  slug: string;
  autoGenerated: boolean;
  source: "provided" | "name" | "fallback";
};

/** Resolve slug from explicit value or name/title — never returns empty. */
export function resolveSlug(params: {
  name?: string | null;
  title?: string | null;
  slug?: string | null;
  fallbackPrefix?: string;
}): SlugResolveResult {
  const label = safeTrim(params.name) || safeTrim(params.title);
  const providedRaw = safeTrim(params.slug);
  const provided = slugify(providedRaw);

  if (provided.length >= 2) {
    return {
      slug: provided,
      autoGenerated: !providedRaw,
      source: providedRaw ? "provided" : "name",
    };
  }

  const fromName = slugify(label);
  if (fromName.length >= 2) {
    return { slug: fromName, autoGenerated: true, source: "name" };
  }

  const prefix = slugify(params.fallbackPrefix) || "item";
  return {
    slug: `${prefix}-${Date.now().toString(36)}`,
    autoGenerated: true,
    source: "fallback",
  };
}

export async function ensureUniqueSlug(
  base: string,
  exists: (slug: string) => Promise<boolean>
): Promise<string> {
  let candidate = base;
  let i = 0;
  while (await exists(candidate)) {
    candidate = `${base}-${++i}`;
    if (i > 200) throw new Error("Could not generate a unique slug");
  }
  return candidate;
}

/** Zod: empty/null slug input → undefined (skip min-length until resolveSlug). */
export const zSlugInput = z.preprocess(
  (v) => {
    const t = safeTrim(v);
    return t || undefined;
  },
  z
    .string()
    .regex(/^[a-z0-9-]+$/, "Slug may only contain lowercase letters, numbers, and hyphens")
    .min(2)
    .max(120)
    .optional()
);

export const SLUG_AUTO_GENERATED_MESSAGE =
  "Slug was missing and has been generated automatically.";
