"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createGame, updateGame } from "@/actions/admin/games";
import { uploadViaApi } from "@/lib/upload-client";
import { formatUploadErrorMessage } from "@/lib/upload-errors";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { toast } from "@/hooks/use-toast";
import { STORAGE } from "@/lib/storage";
import { useSlugField } from "@/hooks/use-slug-field";
import { SLUG_AUTO_GENERATED_MESSAGE } from "@/lib/slug";
import { compressImage } from "@/lib/image-compress";
import { SafeImage } from "@/components/ui/safe-image";

type GameData = {
  id?: string;
  name: string;
  slug: string;
  description?: string | null;
  shortDescription?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  isFeatured: boolean;
  isActive: boolean;
  sortOrder: number;
  logoUrl?: string | null;
  backgroundUrl?: string | null;
  iconUrl?: string | null;
  bannerUrl?: string | null;
  coverUrl?: string | null;
};

export function GameForm({ locale, game }: { locale: string; game?: GameData }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [name, setName] = useState(game?.name ?? "");
  const { slug, setSlug } = useSlugField(name, game?.slug ?? "");

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const form = new FormData(e.currentTarget);
    const slugValue = slug.trim() || undefined;
    const payload = {
      name: form.get("name") as string,
      slug: slugValue,
      description: (form.get("description") as string) || undefined,
      shortDescription: (form.get("shortDescription") as string) || undefined,
      seoTitle: (form.get("seoTitle") as string) || undefined,
      seoDescription: (form.get("seoDescription") as string) || undefined,
      isFeatured: form.get("isFeatured") === "on",
      isActive: form.get("isActive") === "on",
      sortOrder: Number(form.get("sortOrder") || 0),
    };

    startTransition(async () => {
      const result = game?.id
        ? await updateGame(game.id, payload)
        : await createGame(payload);

      if (result.success) {
        const autoSlug =
          !game?.id &&
          result.data &&
          typeof result.data === "object" &&
          "slugAutoGenerated" in result.data &&
          result.data.slugAutoGenerated;
        toast({
          title: game?.id ? "Game updated" : "Game created",
          description: autoSlug ? SLUG_AUTO_GENERATED_MESSAGE : undefined,
        });
        router.push(`/${locale}/admin/games`);
        router.refresh();
      } else {
        toast({ title: "Error", description: result.error, variant: "destructive" });
      }
    });
  }

  async function uploadAsset(type: "icon" | "banner" | "cover" | "logo" | "background", file: File) {
    if (!game?.id) {
      toast({ title: "Save game first", variant: "destructive" });
      return;
    }
    try {
      const compressed = await compressImage(file, 0.85, type === "icon" ? 512 : 1920).catch(() => file);
      await uploadViaApi({
        file: compressed,
        purpose: "game-asset",
        gameId: game.id,
        assetType: type,
      });
      toast({ title: `${type} uploaded` });
      router.refresh();
    } catch (err) {
      toast({
        title: "Upload failed",
        description: formatUploadErrorMessage(err),
        variant: "destructive",
      });
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6 max-w-2xl">
      <Card className="glass p-6 space-y-4">
        <div>
          <label className="text-sm font-medium">Name</label>
          <Input name="name" value={name} onChange={(e) => setName(e.target.value)} required className="mt-1" />
        </div>
        <div>
          <label className="text-sm font-medium">Slug</label>
          <Input
            name="slug"
            value={slug}
            onChange={(e) => setSlug(e.target.value)}
            placeholder="auto-generated from name"
            className="mt-1 font-mono text-sm"
          />
          <p className="text-xs text-muted-foreground mt-1">Leave blank to auto-generate from the game name.</p>
        </div>
        <div>
          <label className="text-sm font-medium">Short Description</label>
          <Input name="shortDescription" defaultValue={game?.shortDescription ?? ""} maxLength={300} className="mt-1" placeholder="Brief tagline for cards and SEO" />
        </div>
        <div>
          <label className="text-sm font-medium">Description</label>
          <Textarea name="description" defaultValue={game?.description ?? ""} rows={4} className="mt-1" />
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="text-sm font-medium">SEO Title</label>
            <Input name="seoTitle" defaultValue={game?.seoTitle ?? ""} className="mt-1" />
          </div>
          <div>
            <label className="text-sm font-medium">Sort Order</label>
            <Input name="sortOrder" type="number" defaultValue={game?.sortOrder ?? 0} className="mt-1" />
          </div>
        </div>
        <div>
          <label className="text-sm font-medium">SEO Description</label>
          <Textarea name="seoDescription" defaultValue={game?.seoDescription ?? ""} rows={2} className="mt-1" />
        </div>
        <div className="flex gap-6">
          <label className="flex items-center gap-2 text-sm">
            <input type="checkbox" name="isFeatured" defaultChecked={game?.isFeatured} />
            Featured
          </label>
          <label className="flex items-center gap-2 text-sm">
            <input type="checkbox" name="isActive" defaultChecked={game?.isActive ?? true} />
            Active
          </label>
        </div>
      </Card>

      {game?.id && (
        <Card className="glass p-6 space-y-4">
          <p className="font-medium">Assets</p>
          <p className="text-xs text-muted-foreground">Uploaded to {STORAGE.cdn} · WebP compression applied on upload</p>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div>
              <label className="text-xs text-muted-foreground">
                Logo
                <span className="mt-0.5 block font-normal text-muted-foreground/80">
                  Navbar &amp; hover menu
                </span>
              </label>
              {game.logoUrl && (
                <div className="relative mt-1 mb-2 h-14 w-14 rounded-lg overflow-hidden border border-border/50">
                  <SafeImage src={game.logoUrl} alt="" fill className="object-contain p-1" sizes="56px" />
                </div>
              )}
              <Input
                type="file"
                accept="image/*"
                className="mt-1"
                onChange={(e) => e.target.files?.[0] && uploadAsset("logo", e.target.files[0])}
              />
            </div>
            <div>
              <label className="text-xs text-muted-foreground">Icon (square)</label>
              {game.iconUrl && (
                <div className="relative mt-1 mb-2 h-14 w-14 rounded-lg overflow-hidden border border-border/50">
                  <SafeImage src={game.iconUrl} alt="" fill className="object-cover" sizes="56px" />
                </div>
              )}
              <Input
                type="file"
                accept="image/*"
                className="mt-1"
                onChange={(e) => e.target.files?.[0] && uploadAsset("icon", e.target.files[0])}
              />
            </div>
            <div>
              <label className="text-xs text-muted-foreground">
                Cover portrait
                <span className="mt-0.5 block font-normal text-muted-foreground/80">
                  Games overview · 1000×1500 or 2:3 ratio
                </span>
              </label>
              {game.coverUrl && (
                <div className="relative mt-1 mb-2 h-20 w-14 rounded-lg overflow-hidden border border-border/50">
                  <SafeImage src={game.coverUrl} alt="" fill className="object-cover" sizes="56px" />
                </div>
              )}
              <Input
                type="file"
                accept="image/*"
                className="mt-1"
                onChange={(e) => e.target.files?.[0] && uploadAsset("cover", e.target.files[0])}
              />
            </div>
            <div>
              <label className="text-xs text-muted-foreground">
                Banner (wide hero)
                <span className="mt-0.5 block font-normal text-muted-foreground/80">
                  Game detail page header
                </span>
              </label>
              {game.bannerUrl && (
                <div className="relative mt-1 mb-2 h-16 w-full rounded-lg overflow-hidden border border-border/50">
                  <SafeImage src={game.bannerUrl} alt="" fill className="object-cover" sizes="200px" />
                </div>
              )}
              <Input
                type="file"
                accept="image/*"
                className="mt-1"
                onChange={(e) => e.target.files?.[0] && uploadAsset("banner", e.target.files[0])}
              />
            </div>
            <div className="sm:col-span-2">
              <label className="text-xs text-muted-foreground">Background (game page)</label>
              {game.backgroundUrl && (
                <div className="relative mt-1 mb-2 h-16 w-full rounded-lg overflow-hidden border border-border/50">
                  <SafeImage src={game.backgroundUrl} alt="" fill className="object-cover" sizes="200px" />
                </div>
              )}
              <Input
                type="file"
                accept="image/*"
                className="mt-1"
                onChange={(e) => e.target.files?.[0] && uploadAsset("background", e.target.files[0])}
              />
            </div>
          </div>
        </Card>
      )}

      <Button type="submit" variant="neon" disabled={pending}>
        {pending ? "Saving..." : game?.id ? "Update Game" : "Create Game"}
      </Button>
    </form>
  );
}
