"use server";

import { revalidatePath, revalidateTag } from "next/cache";
import { z } from "zod";
import { getDb } from "@/lib/db";
import { createAuditLog } from "@/lib/audit";
import { fail, ok, requireActionPermission, actionTry, formatZodError } from "@/lib/action-utils";
import { uploadAsset } from "@/lib/asset-storage";
import { extensionForMime, validateUploadFile } from "@/lib/upload-validation";
import { CACHE_TAGS } from "@/lib/cache";
import { resolveSlug, ensureUniqueSlug, zSlugInput, slugify } from "@/lib/slug";
import type { BannerAlign, BannerDisplayType } from "@prisma/client";

const gameSchema = z.object({
  name: z.string().min(2).max(80),
  slug: zSlugInput,
  description: z.string().max(5000).optional(),
  shortDescription: z.string().max(300).optional(),
  seoTitle: z.string().max(120).optional(),
  seoDescription: z.string().max(300).optional(),
  isFeatured: z.boolean().optional(),
  isActive: z.boolean().optional(),
  sortOrder: z.number().int().optional(),
});

export async function getAdminGames() {
  const { error } = await requireActionPermission("games.write");
  if (error) return error;

  return actionTry(
    async () =>
      (await getDb()).game.findMany({
        orderBy: [{ sortOrder: "asc" }, { name: "asc" }],
        include: { _count: { select: { mods: true, categories: true } } },
      }),
    "games:list"
  );
}

export async function getAdminGame(id: string) {
  const { error } = await requireActionPermission("games.write");
  if (error) return error;

  const game = await (await getDb()).game.findUnique({
    where: { id },
    include: {
      categories: { orderBy: [{ sortOrder: "asc" }, { name: "asc" }] },
      modes: { orderBy: [{ sortOrder: "asc" }, { name: "asc" }] },
      _count: { select: { mods: true, categories: true, modes: true } },
    },
  });
  if (!game) return fail("Game not found");
  return ok(game);
}

export async function createGame(input: z.infer<typeof gameSchema>) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  const parsed = gameSchema.safeParse(input);
  if (!parsed.success) return fail(formatZodError(parsed.error));

  return actionTry(async () => {
    const resolved = resolveSlug({ name: parsed.data.name, slug: parsed.data.slug });
    const slug = await ensureUniqueSlug(resolved.slug, async (s) =>
      Boolean(await (await getDb()).game.findUnique({ where: { slug: s } }))
    );

    const game = await (await getDb()).game.create({
      data: {
        name: parsed.data.name,
        slug,
        description: parsed.data.description,
        shortDescription: parsed.data.shortDescription,
        seoTitle: parsed.data.seoTitle ?? parsed.data.name,
        seoDescription: parsed.data.seoDescription ?? parsed.data.description?.slice(0, 160),
        isFeatured: parsed.data.isFeatured ?? false,
        isActive: parsed.data.isActive ?? true,
        sortOrder: parsed.data.sortOrder ?? 0,
      },
    });

    await createAuditLog({
      actorId: user.id,
      action: "game.create",
      entityType: "Game",
      entityId: game.id,
    });

    revalidatePath("/");
    revalidatePath("/games");
    revalidatePath("/admin/games");
    return { ...game, slugAutoGenerated: resolved.autoGenerated };
  }, "games:create");
}

export async function updateGame(id: string, input: z.infer<typeof gameSchema>) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  const parsed = gameSchema.safeParse(input);
  if (!parsed.success) return fail(formatZodError(parsed.error));

  return actionTry(async () => {
    const resolved = resolveSlug({ name: parsed.data.name, slug: parsed.data.slug });
    const slug = parsed.data.slug
      ? await ensureUniqueSlug(resolved.slug, async (s) => {
          const existing = await (await getDb()).game.findUnique({ where: { slug: s } });
          return Boolean(existing && existing.id !== id);
        })
      : undefined;

    const game = await (await getDb()).game.update({
      where: { id },
      data: {
        name: parsed.data.name,
        ...(slug && { slug }),
        description: parsed.data.description,
        shortDescription: parsed.data.shortDescription,
        seoTitle: parsed.data.seoTitle,
        seoDescription: parsed.data.seoDescription,
        isFeatured: parsed.data.isFeatured,
        isActive: parsed.data.isActive,
        sortOrder: parsed.data.sortOrder,
      },
    });

    await createAuditLog({
      actorId: user.id,
      action: "game.update",
      entityType: "Game",
      entityId: id,
    });

    revalidatePath("/");
    revalidatePath("/games");
    revalidatePath(`/games/${game.slug}`);
    revalidatePath("/admin/games");
    return game;
  }, "games:update");
}

export async function deleteGame(id: string) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  return actionTry(async () => {
    const modCount = await (await getDb()).mod.count({ where: { gameId: id } });
    if (modCount > 0) throw new Error("Cannot delete game with existing mods");

    await (await getDb()).game.delete({ where: { id } });

    await createAuditLog({
      actorId: user.id,
      action: "game.delete",
      entityType: "Game",
      entityId: id,
    });

    revalidatePath("/");
    revalidatePath("/admin/games");
  }, "games:delete");
}

export async function uploadGameAsset(
  gameId: string,
  type: "icon" | "banner" | "cover" | "logo" | "background",
  formData: FormData
) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  try {
    const file = formData.get("file") as File;
    const validation = validateUploadFile(file, {
      maxSizeMb: 5,
      allowedTypes: ["image/jpeg", "image/png", "image/webp"],
      label: "Game asset",
    });
    if (!validation.valid) return fail(validation.error);

    const game = await (await getDb()).game.findUnique({ where: { id: gameId } });
    if (!game) return fail("Game not found");

    const buffer = Buffer.from(await file.arrayBuffer());
    const relativePath = `${game.slug}/${type}-${Date.now()}.${extensionForMime(validation.mime)}`;
    const result = await uploadAsset({
      bucket: "games",
      relativePath,
      body: buffer,
      contentType: validation.mime,
    });

    const field =
      type === "icon"
        ? "iconUrl"
        : type === "banner"
          ? "bannerUrl"
          : type === "logo"
            ? "logoUrl"
            : type === "background"
              ? "backgroundUrl"
              : "coverUrl";

    await (await getDb()).game.update({
      where: { id: gameId },
      data: { [field]: result.url },
    });

    await createAuditLog({
      actorId: user.id,
      action: `game.upload_${type}`,
      entityType: "Game",
      entityId: gameId,
    });

    revalidatePath(`/games/${game.slug}`);
    revalidatePath("/admin/games");
    return ok({ url: result.url });
  } catch (err) {
    return fail(err instanceof Error ? err.message : "Upload failed");
  }
}

export async function createGameCategory(
  gameId: string,
  input: { name: string; slug?: string; description?: string; isVisible?: boolean; parentId?: string | null }
) {
  const { error } = await requireActionPermission("games.write");
  if (error) return error;

  const resolved = resolveSlug({ name: input.name, slug: input.slug });
  let slug = resolved.slug;
  if (input.parentId) {
    const parent = await (await getDb()).gameCategory.findUnique({ where: { id: input.parentId } });
    if (!parent || parent.gameId !== gameId) return fail("Invalid parent category");
    slug = `${parent.slug}-${slug}`;
  }

  slug = await ensureUniqueSlug(slug, async (s) =>
    Boolean(
      await (await getDb()).gameCategory.findUnique({
        where: { gameId_slug: { gameId, slug: s } },
      })
    )
  );

  const siblings = await (await getDb()).gameCategory.count({
    where: { gameId, parentId: input.parentId ?? null },
  });

  const category = await (await getDb()).gameCategory.create({
    data: {
      gameId,
      parentId: input.parentId ?? null,
      name: input.name,
      slug,
      description: input.description,
      isVisible: input.isVisible ?? true,
      sortOrder: siblings,
    },
  });

  revalidatePath("/admin/games");
  revalidateTag(CACHE_TAGS.games);
  return ok(category);
}

export async function updateGameCategory(
  categoryId: string,
  input: {
    name?: string;
    slug?: string;
    description?: string;
    sortOrder?: number;
    isVisible?: boolean;
    parentId?: string | null;
    accentColor?: string | null;
  }
) {
  const { error } = await requireActionPermission("games.write");
  if (error) return error;

  const category = await (await getDb()).gameCategory.update({
    where: { id: categoryId },
    data: {
      ...(input.name && { name: input.name }),
      ...(input.slug
        ? { slug: slugify(input.slug) }
        : input.name
          ? { slug: resolveSlug({ name: input.name }).slug }
          : {}),
      ...(input.description !== undefined && { description: input.description }),
      ...(input.sortOrder !== undefined && { sortOrder: input.sortOrder }),
      ...(input.isVisible !== undefined && { isVisible: input.isVisible }),
      ...(input.accentColor !== undefined && { accentColor: input.accentColor }),
    },
    include: { game: { select: { slug: true } } },
  });

  revalidatePath("/admin/games");
  revalidatePath(`/games/${category.game.slug}`);
  revalidateTag(CACHE_TAGS.games);
  return ok(category);
}

export async function deleteGameCategory(categoryId: string) {
  const { error } = await requireActionPermission("games.write");
  if (error) return error;

  const childCount = await (await getDb()).gameCategory.count({ where: { parentId: categoryId } });
  if (childCount > 0) return fail("Delete subcategories first");

  const modCount = await (await getDb()).mod.count({ where: { categoryId } });
  if (modCount > 0) return fail("Category has mods — reassign them first");

  const category = await (await getDb()).gameCategory.delete({
    where: { id: categoryId },
    include: { game: { select: { slug: true } } },
  });

  revalidatePath("/admin/games");
  revalidatePath(`/games/${category.game.slug}`);
  revalidateTag(CACHE_TAGS.games);
  return ok(undefined);
}

export async function reorderCategories(gameId: string, categoryIds: string[]) {
  const { error } = await requireActionPermission("games.write");
  if (error) return error;

  const db = await getDb();
  await db.$transaction(
    categoryIds.map((id, index) =>
      db.gameCategory.update({ where: { id, gameId }, data: { sortOrder: index } })
    )
  );

  revalidatePath("/admin/games");
  revalidateTag(CACHE_TAGS.games);
  return ok(undefined);
}

export async function uploadGameCategoryAsset(
  categoryId: string,
  type: "thumbnail" | "banner" | "icon",
  formData: FormData
) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  try {
    const file = formData.get("file") as File;
    const validation = validateUploadFile(file, {
      maxSizeMb: 5,
      allowedTypes: ["image/jpeg", "image/png", "image/webp"],
      label: "Category asset",
    });
    if (!validation.valid) return fail(validation.error);

    const category = await (await getDb()).gameCategory.findUnique({
      where: { id: categoryId },
      include: { game: { select: { slug: true } } },
    });
    if (!category) return fail("Category not found");

    const buffer = Buffer.from(await file.arrayBuffer());
    const relativePath = `${category.game.slug}/categories/${category.slug}-${type}-${Date.now()}.${extensionForMime(validation.mime)}`;
    const result = await uploadAsset({
      bucket: "games",
      relativePath,
      body: buffer,
      contentType: validation.mime,
    });

    const field =
      type === "thumbnail" ? "thumbnailUrl" : type === "banner" ? "bannerUrl" : "iconUrl";

    await (await getDb()).gameCategory.update({
      where: { id: categoryId },
      data: { [field]: result.url },
    });

    await createAuditLog({
      actorId: user.id,
      action: `game.category.upload_${type}`,
      entityType: "GameCategory",
      entityId: categoryId,
    });

    revalidatePath("/admin/games");
    revalidatePath(`/games/${category.game.slug}`);
    revalidateTag(CACHE_TAGS.games);
    return ok({ url: result.url });
  } catch (err) {
    return fail(err instanceof Error ? err.message : "Upload failed");
  }
}

export async function reorderGames(ids: string[]) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  return actionTry(async () => {
    const db = await getDb();
    await db.$transaction(
      ids.map((id, index) => db.game.update({ where: { id }, data: { sortOrder: index } }))
    );

    await createAuditLog({
      actorId: user.id,
      action: "game.reorder",
      entityType: "Game",
      entityId: "bulk",
    });

    revalidatePath("/");
    revalidatePath("/admin/games");
    revalidateTag(CACHE_TAGS.games);
  }, "games:reorder");
}

const bannerSettingsSchema = z.object({
  bannerDisplayType: z.enum(["SMALL", "FEATURED", "CUSTOM"]),
  bannerHeightPx: z.number().int().min(120).max(800).nullable().optional(),
  bannerFocusX: z.number().min(0).max(100),
  bannerFocusY: z.number().min(0).max(100),
  bannerZoom: z.number().min(1).max(2),
  bannerAlign: z.enum(["CENTER", "TOP", "BOTTOM", "LEFT", "RIGHT"]),
});

export async function updateGameBannerSettings(
  id: string,
  input: z.infer<typeof bannerSettingsSchema>
) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  const parsed = bannerSettingsSchema.safeParse(input);
  if (!parsed.success) return fail(formatZodError(parsed.error));

  return actionTry(async () => {
    const game = await (await getDb()).game.update({
      where: { id },
      data: {
        bannerDisplayType: parsed.data.bannerDisplayType as BannerDisplayType,
        bannerHeightPx: parsed.data.bannerHeightPx ?? null,
        bannerFocusX: parsed.data.bannerFocusX,
        bannerFocusY: parsed.data.bannerFocusY,
        bannerZoom: parsed.data.bannerZoom,
        bannerAlign: parsed.data.bannerAlign as BannerAlign,
      },
    });

    await createAuditLog({
      actorId: user.id,
      action: "game.banner_settings",
      entityType: "Game",
      entityId: id,
    });

    revalidatePath("/admin/games");
    revalidatePath(`/games/${game.slug}`);
    revalidateTag(CACHE_TAGS.games);
    return game;
  }, "games:banner-settings");
}

const modePickerSettingsSchema = z.object({
  modePickerOverlay: z.number().min(0).max(1),
  modePickerBlurPx: z.number().int().min(0).max(64),
  modePickerGlowEnabled: z.boolean(),
  modePickerAnimation: z.enum(["fade", "scale", "slide"]),
  modePickerOpacity: z.number().min(0.3).max(1),
});

export async function updateGameModePickerSettings(
  id: string,
  input: z.infer<typeof modePickerSettingsSchema>
) {
  const { user, error } = await requireActionPermission("games.write");
  if (error) return error;

  const parsed = modePickerSettingsSchema.safeParse(input);
  if (!parsed.success) return fail(formatZodError(parsed.error));

  return actionTry(async () => {
    const game = await (await getDb()).game.update({
      where: { id },
      data: parsed.data,
    });

    await createAuditLog({
      actorId: user.id,
      action: "game.mode_picker_settings",
      entityType: "Game",
      entityId: id,
    });

    revalidatePath("/admin/games");
    revalidatePath(`/games/${game.slug}`);
    revalidateTag(CACHE_TAGS.games);
    return game;
  }, "games:mode-picker-settings");
}
